security:
  basic:
    enabled: false

management:
  security:
    enabled: false

logging:
  level:
    io:
      pivotal: DEBUG
user.serviceUrl: user-service/user
catalog.serviceUrl: catalog-service/catalog
gateway.serviceId: gateway-application
